#include "../Common.ush"
#include "../ScreenPass.ush"
#include "../PostProcessCommon.ush"
#include "../TextureSampling.ush"

Texture2D PointSceneColorTexture;
SamplerState PointSceneColorSampler;
void MainPS(noperspective float4 UVAndScreenPos : TEXCOORD0, float4 SvPosition : SV_POSITION, out float4 OutColor : SV_Target0)
{
	OutColor = Texture2DSample(PointSceneColorTexture, PointSceneColorSampler, UVAndScreenPos.xy);
}
